apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: apr4-testnewgitops-llamacpp-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr4-testnewgitops-llamacpp-2
  name: apr4-testnewgitops-llamacpp-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
